#!/usr/bin/with-contenv bash
# shellcheck disable=SC1008

printf "[cont-init.d] Fixing Folder Permissions - Config [${DEEMIX_DATA_DIR}] Folder\n"

# mkdir -p ${DEEMIX_DATA_DIR}
# chown -R abc:abc ${DEEMIX_DATA_DIR}

if [ -n "${DISABLE_OWNERSHIP_CHECK}" ]; then
	printf "[cont-init.d] Download Folder Ownership Check disabled by Environment Variable\n"
else
	printf "[cont-init.d] Fixing Folder Permissions - Downloads [${DEEMIX_MUSIC_DIR}] Folder\n"
	find ${DEEMIX_MUSIC_DIR} -type d -exec chown abc:abc {} +
fi

# Fix misconfigured download locations. The container's download map is always /downloads.
if [ -f "${DEEMIX_DATA_DIR}/config.json" ]; then
	printf '[cont-init.d] Fixing download location\n'
	jq '.downloadLocation = "/downloads"' ${DEEMIX_DATA_DIR}/config.json >tmp.$$.json && mv tmp.$$.json ${DEEMIX_DATA_DIR}/config.json
	chown abc:abc ${DEEMIX_DATA_DIR}/config.json
fi