#!/usr/bin/with-contenv bash

printf '[cont-init.d] Setting deemix-server\n'

chmod +x /deemix-server

printf '[cont-init.d] Creating abc:abc user:group 0:0\n'

echo "abc:x:0:0:Linux User,,,:/home/abc:/bin/ash" >> /etc/passwd
echo "abc:x:1000:" >> /etc/group
