#!/usr/bin/with-contenv bash
# shellcheck disable=SC1008

echo "[services.d] Variables"
echo "DEEMIX_SERVER_PORT: ${DEEMIX_SERVER_PORT}"
echo "DEEMIX_DATA_DIR: ${DEEMIX_DATA_DIR}"
echo "DEEMIX_MUSIC_DIR: ${DEEMIX_MUSIC_DIR}"
echo "DEEMIX_HOST: ${DEEMIX_HOST}"
echo "DEEMIX_SINGLE_USER: ${DEEMIX_SINGLE_USER}"
echo "PUID: ${PUID}"
echo "PGID: ${PGID}"
echo "UMASK_SET: ${UMASK_SET}"

if [ ! -f ${DEEMIX_DATA_DIR}/config.json ]; then
    cp /deemix/config.json ${DEEMIX_DATA_DIR}
fi

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

echo "[services.d] Starting Deemix"
s6-setuidgid abc node /app/webui/dist/main.js