#!/usr/bin/with-contenv bash
# shellcheck disable=SC1008

echo "[services.d]\nVariables"
echo "DEEMIX_SERVER_PORT: ${DEEMIX_SERVER_PORT}"
echo "DEEMIX_DATA_DIR: ${DEEMIX_DATA_DIR}"
echo "DEEMIX_MUSIC_DIR: ${DEEMIX_MUSIC_DIR}"
echo "DEEMIX_HOST: ${DEEMIX_HOST}"
echo "DEEMIX_SINGLE_USER: ${DEEMIX_SINGLE_USER}"
echo "PUID: ${PUID}"
echo "PGID: ${PGID}"
echo "UMASK_SET: ${UMASK_SET}"

printf "\n${DEEMIX_DATA_DIR}:\n"
ls -la ${DEEMIX_DATA_DIR}

printf "\n/config:\n"
ls -la /config

printf "\n/config/addons_config:\n"
ls -la /config/addons_config

printf "\n/homeassistant:\n"
ls -la /homeassistant

printf "\nroot:\n"
ls -la /

#if [ ! -f /config/deemix/config.json ]; then
#    cp /deemix/config.json /config/deemix/config.json
#fi

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

echo "[services.d] Starting Deemix"
s6-setuidgid abc node /app/webui/dist/main.js